### ISSUE TITLE
could not open port '/dev/ttyACM0'

### ISSUE THREAD

**Issue by XOnanoSmartfoam** [nesl/tinyodom#2]
I am drawing a blank again on another error and wonder if there is anyone that knows how to overcome this. I am using a windows 11 machine but cannot figure out where '/dev/ttyACM0' would be and what files would be required.

Here is the complete error:
---------------------------------------------------------------------------
SerialException                           Traceback (most recent call last)
Cell In[8], line 61
     59 tuner = Tuner(param_dict, objfunc,conf_Dict)
     60 all_runs = []
---> 61 results = tuner.maximize()
     62 all_runs.append(results)
     63 save_res(all_runs,log_file_name[0:-4]+'.p')

File [c:\Users\jakem\AppData\Local\Programs\Python\Python310\lib\site-packages\mango\tuner.py:152](file:///C:/Users/jakem/AppData/Local/Programs/Python/Python310/lib/site-packages/mango/tuner.py:152), in Tuner.maximize(self)
    151 def maximize(self):
--> 152     return self.run()

File [c:\Users\jakem\AppData\Local\Programs\Python\Python310\lib\site-packages\mango\tuner.py:143](file:///C:/Users/jakem/AppData/Local/Programs/Python/Python310/lib/site-packages/mango/tuner.py:143), in Tuner.run(self)
    141 def run(self):
    142     if self.config.is_bayesian:
--> 143         self.results = self.runBayesianOptimizer()
    144     elif self.config.is_random:
    145         self.results = self.runRandomOptimizer()

File [c:\Users\jakem\AppData\Local\Programs\Python\Python310\lib\site-packages\mango\tuner.py:185](file:///C:/Users/jakem/AppData/Local/Programs/Python/Python310/lib/site-packages/mango/tuner.py:185), in Tuner.runBayesianOptimizer(self)
    182 def runBayesianOptimizer(self):
    183     results = dict()
--> 185     X_list, Y_list, X_tried = self.run_initial()
    188     # evaluated hyper parameters are used
    189     X_init = self.ds.convert_GP_space(X_list)

File [c:\Users\jakem\AppData\Local\Programs\Python\Python310\lib\site-packages\mango\tuner.py:166](file:///C:/Users/jakem/AppData/Local/Programs/Python/Python310/lib/site-packages/mango/tuner.py:166), in Tuner.run_initial(self)
    163 else:
    164     # getting first few random values
    165     X_tried = self.ds.get_random_sample(self.config.initial_random)
--> 166     X_list, Y_list = self.runUserObjective(X_tried)
    168     # in case initial random results are invalid try different samples
    169     n_tries = 1

File [c:\Users\jakem\AppData\Local\Programs\Python\Python310\lib\site-packages\mango\tuner.py:337](file:///C:/Users/jakem/AppData/Local/Programs/Python/Python310/lib/site-packages/mango/tuner.py:337), in Tuner.runUserObjective(self, X_next_PS)
    334 def runUserObjective(self, X_next_PS):
    335     # initially assuming entire X_next_PS is evaluated and returned results are only Y values
    336     X_list_evaluated = X_next_PS
--> 337     results = self.objective_function(X_next_PS)
    338     Y_list_evaluated = results
    340     # if result is a tuple, then there is possibility that partial values are evaluated

Cell In[8], line 44, in objfunc(args_list)
     41 norm_flag=hyper_par['norm_flag']
     42 dil_list = hyper_par['dil_list']
---> 44 objective = objective_NN(epochs=model_epochs,nb_filters=nb_filters,kernel_size=kernel_size,
     45                          dilations=dil_list,
     46                          dropout_rate=dropout_rate,use_skip_connections=use_skip_connections,
     47                          norm_flag=norm_flag)
     48 objective_evaluated.append(objective)
     50 end_time = time.time()

Cell In[7], line 33, in objective_NN(epochs, nb_filters, kernel_size, dilations, dropout_rate, use_skip_connections, norm_flag)
     31 if(HIL==True):
     32     convert_to_cpp_model(dirpath)
---> 33     RAM, Flash, Latency, idealArenaSize, errorCode = HIL_controller(dirpath=dirpath,
     34                                                                    chosen_device=device,
     35                                                                    window_size=window_size, 
     36                                                                 number_of_channels = input_dim,
     37                                                                quantization=quantization)     
     38     score = -5.0
     39     if(Flash==-1):

File [c:\Users\jakem\OneDrive](file:///C:/Users/jakem/OneDrive) - xonano.com\Documents\Python Scripts\TinyOdom\OxIOD\hardware_utils.py:89, in HIL_controller(dirpath, chosen_device, window_size, number_of_channels, quantization)
     87 j = 0
     88 while(masterError==0):
---> 89     RAM, Flash, Latency, err_flag = HIL_spec(dirpath,chosen_device,arenaSizes,j,
     90                                              window_size,number_of_channels,quantization=False)
     91     print('Before change:',masterError)            
     92     if(err_flag == 0): #already got minimum required arena size, everything ok

File [c:\Users\jakem\OneDrive](file:///C:/Users/jakem/OneDrive) - xonano.com\Documents\Python Scripts\TinyOdom\OxIOD\hardware_utils.py:30, in HIL_spec(dirpath, chosen_device, arenaSizes, idx, window_size, number_of_channels, quantization)
     28 def HIL_spec(dirpath="tinyodom_tcn/",chosen_device="NUCLEO_F746ZG",
     29              arenaSizes=np.arange(10,300,30),idx=0,window_size=200,number_of_channels=10,quantization=False):
---> 30     ser = serial.Serial('/dev/ttyACM0') #COM Port where board is attached
     31     RAM = -1
     32     Flash = -1

File [c:\Users\jakem\AppData\Local\Programs\Python\Python310\lib\site-packages\serial\serialwin32.py:33](file:///C:/Users/jakem/AppData/Local/Programs/Python/Python310/lib/site-packages/serial/serialwin32.py:33), in Serial.__init__(self, *args, **kwargs)
     31 self._overlapped_read = None
     32 self._overlapped_write = None
---> 33 super(Serial, self).__init__(*args, **kwargs)

File [c:\Users\jakem\AppData\Local\Programs\Python\Python310\lib\site-packages\serial\serialutil.py:244](file:///C:/Users/jakem/AppData/Local/Programs/Python/Python310/lib/site-packages/serial/serialutil.py:244), in SerialBase.__init__(self, port, baudrate, bytesize, parity, stopbits, timeout, xonxoff, rtscts, write_timeout, dsrdtr, inter_byte_timeout, exclusive, **kwargs)
    241     raise ValueError('unexpected keyword arguments: {!r}'.format(kwargs))
    243 if port is not None:
--> 244     self.open()

File [c:\Users\jakem\AppData\Local\Programs\Python\Python310\lib\site-packages\serial\serialwin32.py:64](file:///C:/Users/jakem/AppData/Local/Programs/Python/Python310/lib/site-packages/serial/serialwin32.py:64), in Serial.open(self)
     62 if self._port_handle == win32.INVALID_HANDLE_VALUE:
     63     self._port_handle = None    # 'cause __del__ is called anyway
---> 64     raise SerialException("could not open port {!r}: {!r}".format(self.portstr, ctypes.WinError()))
     66 try:
     67     self._overlapped_read = win32.OVERLAPPED()

SerialException: could not open port '/dev/ttyACM0': FileNotFoundError(2, 'The system cannot find the path specified.', None, 3)

**Comment by XOnanoSmartfoam** [comment]
I just figured it out. This issue is due to me not having the MC connected to my computer.

**Comment by swapnilsayansaha** [comment]
Ya you are right. If you use platform-in-the-loop, the microcontroller must be connected to the computer.

I didn't design the framework to run on Windows. I did list a GPU workstation with Ubuntu as one of the requirements. I am not sure that even if you connect the MC to try platform-in-the-loop if the Mbed CLI or the serial communication code would work properly on Windows. For instance, ```/dev/ttyACM0``` is a Ubuntu specific USB interface, for Mac or Windows it's different.
